project:
  name: aws-digital-content-creation-render-environment
  owner: rezabekf@amazon.co.uk
  package_lambda: false
  regions:
    - us-east-1
    - us-east-2
    - us-west-2
    - ap-northeast-1
    - ap-southeast-1
    - eu-central-1
    - eu-west-1
tests:
  test-g4dn.xlarge:
    template: ./cfn/packaged.template
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      StackName: TaskcatStack
      EC2UserPassword: $[taskcat_genpass_8A]
      WorkstationInstanceType: g4dn.xlarge
    regions:
      - us-east-1
      - eu-west-1

  test-m5dn.xlarge:
    auth:
      default: builders
    template: ./cfn/packaged.template
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      StackName: TaskcatStack
      EC2UserPassword: $[taskcat_genpass_8A]
      WorkstationInstanceType: m5dn.xlarge
    regions:
      - us-east-1
      - eu-west-1
